version: 0.0
os: linux

files:
  - source: target/application.jar
    destination: /opt/application/

permissions:
  - object: /opt/application/application.jar
    pattern: "**"
    owner: ubuntu
    group: ubuntu
hooks:
  ApplicationStop:
    - location: stop_server.sh
      timeout: 60
      runas: ubuntu
  BeforeInstall:
    - location: before_install.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: after_install.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: start_server.sh
      timeout: 60
      runas: ubuntu
