version: 0.0
os: linux
files:
  - source: /application.zip
    destination: /opt/application/
    overwrite: true

permissions:
  - object: /opt/application/application.jar
    pattern: "**/*"
    mode: 755
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ubuntu
