version: 0.0
os: linux

files:
  - source: deploy/application.jar
    destination: /opt/application  # Path on the EC2 instance where JAR will be deployed

permissions:
  - object: /opt/application/application.jar
    pattern: "**"
    owner: ec2-user  # Update with appropriate user
    group: ec2-user  # Update with appropriate group

hooks:
  ApplicationStop:
    - location: stop_server.sh
      timeout: 60
      runas: root

  BeforeInstall:
    - location: before_install.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: after_install.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: start_server.sh
      timeout: 60
      runas: root
