version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - apt-get update
      - apt-get install -y wget gnupg
      - wget -O- https://apt.corretto.aws/corretto.key | apt-key add -
      - add-apt-repository 'deb https://apt.corretto.aws stable main'
      - apt-get update
      - apt-get install -y java-11-amazon-corretto-jdk maven

  pre_build:
    commands:
      - echo Pre-build phase...
      - mvn clean  # Clean up any existing build artifacts

  build:
    commands:
      - echo Build phase...
      - mvn package --file pom.xml  # Build your Maven project

  post_build:
    commands:
      - echo Post-build phase...
      - echo Build completed successfully.

artifacts:
  files:
    - "**/*"  # Assuming your built jar is located in the target directory
