version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - sudo apt-get update
      - sudo apt-get install -y wget gnupg
      - wget -O- https://apt.corretto.aws/corretto.key | sudo apt-key add -
      - sudo add-apt-repository 'deb https://apt.corretto.aws stable main'
      - sudo apt-get update
      - sudo apt-get install -y java-11-amazon-corretto-jdk maven

  build:
    commands:
      - mvn clean package --file pom.xml
      - chmod +x target/before_install.sh  # Adjust path as per your project structure

artifacts:
  files:
    - '**/*'
  discard-paths: yes
  base-directory: target
  name: application.zip
